### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by michafrometa** [michafrometa/Gateways#5]

**Comment by cruzatadelacruzc** [comment]
Los Test que ejecutan metodo POST,PUT,DELETE no corren debido a que no se le inyecta el codigo csrf ejemplo: `restGatewayMockMvc.perform(delete("/api/gateways/{id}", gateway.getId()).with(csrf())`

**Comment by cruzatadelacruzc** [comment]
Test **createGateway** no se ejecuta de forma satifactoria porque la URI debe terminar en **/**. Debido a que la URI del endpoint en la clase GatewayResource es **@PostMapping("/")**. Entoces al ejecutar el test devuelve el satutus code 405(Metodo no soportado). Solucion: `restGatewayMockMvc.perform(post("/api/gateways/").with(csrf())`

**Comment by michafrometa** [comment]
A pesar de estar mal redactado, este issue se refería a la necesidad de implementar correctamente Test unitarios, de integración, etc. Considero que he cumplido con su cometido. Ejej
